/*global history */
	var oMandt;

sap.ui.define([
	"sap/ui/core/mvc/Controller",
	"sap/ui/core/routing/History",
	"sap/m/PDFViewer"
], function (Controller, History, PDFViewer) {
	"use strict";

	return Controller.extend("CRUD_EXP.CRUD_Exp.controller.BaseController", {
		/**
		 * Convenience method for accessing the router in every controller of the application.
		 * @public
		 * @returns {sap.ui.core.routing.Router} the router for this component
		 */
		getRouter: function () {
			return this.getOwnerComponent().getRouter();
		},

		/**
		 * Convenience method for getting the view model by name in every controller of the application.
		 * @public
		 * @param {string} sName the model name
		 * @returns {sap.ui.model.Model} the model instance
		 */
		getModel: function (sName) {
			return this.getView().getModel(sName);
		},

		/**
		 * Convenience method for setting the view model in every controller of the application.
		 * @public
		 * @param {sap.ui.model.Model} oModel the model instance
		 * @param {string} sName the model name
		 * @returns {sap.ui.mvc.View} the view instance
		 */
		setModel: function (oModel, sName) {
			return this.getView().setModel(oModel, sName);
		},

		/**
		 * Convenience method for getting the resource bundle.
		 * @public
		 * @returns {sap.ui.model.resource.ResourceModel} the resourceModel of the component
		 */
		getResourceBundle: function () {
			return this.getOwnerComponent().getModel("i18n").getResourceBundle();
		},

		/**
		 * Event handler  for navigating back.
		 * It checks if there is a history entry. If yes, history.go(-1) will happen.
		 * If not, it will replace the current entry of the browser history with the master route.
		 * @public
		 */
		onNavBack: function () {
			var sPreviousHash = History.getInstance().getPreviousHash();

			if (sPreviousHash !== undefined) {
				// The history contains a previous entry
				history.go(-1);
			} else {
				// Otherwise we go backwards with a forward history
				var bReplace = true;
				this.getRouter().navTo("master", {}, bReplace);
			}
		},
		
		 onAddDocument: function (oEvent) {
		//This code was generated by the layout editor.
		 	if(! this.oAttachDialogD){
		 		this.oAttachDialogD = sap.ui.xmlfragment("CRUD_EXP.CRUD_Exp.view.AddFile",this.getView().getController());
		 		this.getView().addDependent(this.oAttachDialogD);
		 		this.oAttachDialogD.setResizable(false);
		 	}
		 	this.oAttachDialogD.open();
		},
		
		onCloseAttachDialogDoc: function (oEvent){
			var oFileUploader = sap.ui.getCore().byId("AttachUploader");
			var oTipDoc = sap.ui.getCore().byId("TipDoc");
			oFileUploader.setValue("");
			oTipDoc.setSelectedKey("");
			this.oAttachDialogD.close();
		},

		_checkDocFields: function() {
			var oTipDoc = sap.ui.getCore().byId("TipDoc").getSelectedKey();
			if ( oTipDoc === "") {
				sap.m.MessageToast.show("El tipus de document es obligatori");
				return false;
			}
			var oFileUploader = sap.ui.getCore().byId("AttachUploader");
			if (!oFileUploader.getValue()) {
				sap.m.MessageToast.show("No s'ha seleccionat cap fitxer");
				return false;
			}
			return true;
		},
		
		attachUpload: function(oData){
			var oTipDoc = sap.ui.getCore().byId("TipDoc").getSelectedKey();
			var oFileUploader = sap.ui.getCore().byId("AttachUploader");
			this.docData = oData.getData();
			var token;
			var file = jQuery.sap.domById(oFileUploader.getId() + "-fu").files[0];
			var base64_marker = "data:" + file.type + ";base64,";
			var reader = new FileReader();
			var that = this;
			reader.onload = function (theFile) {
				return function (evt) {
					var base64Index = evt.target.result.indexOf(base64_marker) + base64_marker.length;
					var base64 = evt.target.result.substring(base64Index);
					var sTasksService = window.location.origin + "/sap/opu/odata/sap/ZD_EXP_CONTR_SRV/" + that.docData.entity;
					var sAttachService = window.location.origin + "/sap/opu/odata/sap/ZD_EXP_CONTR_SRV/DocumentSet";
					var slug = that.docData.Codiexp + "|" + 
							   that.docData.Codilot + "|" + 
							   that.docData.Codiofer + "|" + 
							   that.docData.Tipsc + "|" + 
							   that.docData.Numsc + "|" + 
							   oTipDoc + "|" +
							   file.name + "|" + file.type;
					$.ajaxSetup({
						cache: false
					});
					jQuery.ajax({
						url: sTasksService,
						type: "GET",
						async: false,
						beforeSend: function (xhr) {
							xhr.setRequestHeader("X-CSRF-Token", "Fetch");
						},
						success: function (data, textStatus, XMLHttpRequest) {
							token = XMLHttpRequest.getResponseHeader("X-CSRF-Token");
						}
					});
					$.ajaxSetup({
						cache: false
					});
					jQuery.ajax({
						url: sAttachService,
						async: false,
						dataType: "json",
						cache: false,
						data: base64,
						type: "POST",
						beforeSend: function (xhr) {
							xhr.setRequestHeader("X-CSRF-Token", token);
							xhr.setRequestHeader("Content-Type", file.type);
							xhr.setRequestHeader("slug", slug);
							xhr.setRequestHeader("Codiexp", that.docData.Codiexp);
						},
						success: function (odata) {
							sap.m.MessageToast.show("Fitxer adjuntat");
							oFileUploader.setValue("");
						},
						error: function (odata) {
							sap.m.MessageToast.show("Error al adjuntar el fitxer");
						}
					});
				};
			}(file);
			reader.readAsDataURL(file);
		},
		
		getFile: function(oEvent) {
			var oItem = oEvent.getParameter("listItem") || oEvent.getSource();
			var oCodiexp = oItem.getBindingContext().getProperty("Codiexp");
			var oCodilot = oItem.getBindingContext().getProperty("Codilot");
			var oCodiofer = oItem.getBindingContext().getProperty("Codiofer");
			var oTipsc = oItem.getBindingContext().getProperty("Tipsc");
			var oNumsc = oItem.getBindingContext().getProperty("Numsc");
			var oComptador = oItem.getBindingContext().getProperty('Comptador');

			var path = 
				"/sap/opu/odata/sap/ZD_EXP_CONTR_SRV/DocumentSet(Codiexp='" + oCodiexp + 
				"',Codilot='" + oCodilot +
				"',Codiofer='" + oCodiofer +
				"',Tipsc='" + oTipsc +
				"',Numsc='" + oNumsc +
				"',Comptador='" + oComptador + "')/$value";

			try {
				window.open(encodeURI(path));
				} catch (e) { // Error in case of any failures to be catched }
					}

			// CODI PER VISUALITZAR PDF AMB UN POPUP
			//this._pdfViewer = new PDFViewer();
			//this.getView().addDependent(this._pdfViewer);
			//var oUrl = window.location.origin + path;
			//this._pdfViewer.setSource(oUrl);
			//this._pdfViewer.setTitle(oFilename);
			//this._pdfViewer.open();
		},
		
		calcIVA: function(importSI,IVA,importIVA) {
			var oPresLic = this.getView().byId(importSI).getValue();
			var oTipIVA = this.getView().byId(IVA).getSelectedItem().getKey();
			var oPresLicIVA;
			
			if (oPresLic !== "0,00" && oTipIVA !== ""){
				oPresLic = oPresLic.replace(/[.*+?^${}()|[\]\\]/g,'');
				oPresLic = oPresLic.replace(",","");
				var tantPerCent=0;
				switch(oTipIVA) {
					case "N1":
						tantPerCent=4;
						break;
					case "N7":
						tantPerCent=10;
						break;
					case "N8":
						tantPerCent=21;
						break;
					case "S1":
						tantPerCent=4;
						break;
					case "S7":
						tantPerCent=10;
						break;
					case "S8":
						tantPerCent=21;
						break;
				}
				if (tantPerCent===0){
					oPresLicIVA = oPresLic;
				} else {
					var tantPerCent2 = 1 + tantPerCent/100;
					oPresLicIVA = Math.round(oPresLic * tantPerCent2);
				}
				oPresLicIVA=oPresLicIVA/100;
				var oPresLicIVA2;
				oPresLicIVA2=oPresLicIVA.toString();
				oPresLicIVA2=oPresLicIVA2.replace(".",",");
				this.getView().byId(importIVA).setValue(oPresLicIVA2);
			} else {
				this.getView().byId(importIVA).setValue(0);
			}
		},
		
		checkOfeAdj: function (codiexp,codilot) {
			var oDatVal = this.getView().getBindingContext().getModel();
			var oDatPro = oDatVal.getProperty("/");
			var oDatNom = Object.getOwnPropertyNames(oDatPro);
			
 			for (var i = 0; i < oDatNom.length; i++) {
 				if ( oDatNom[i].indexOf("OfeSet") >= 0 && 
 					 oDatNom[i].indexOf(codiexp) >= 0 && 
 					 oDatNom[i].indexOf(codilot) >= 0 &&
 					 oDatPro[oDatNom[i]].Adjudicat === true ) {
 					return true;
 				}
 			}
 			
 			return false;
		}
		
	});

});